# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-07 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u767b\u9332\u65e5')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\u5909\u66f4\u65e5')),
                ('result_code', models.IntegerField(blank=True, default=0, verbose_name='\u7d50\u679c\u30b3\u30fc\u30c9')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u767b\u9332\u65e5')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\u5909\u66f4\u65e5')),
                ('name', models.CharField(max_length=255, verbose_name='\u30c6\u30b9\u30c8')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u767b\u9332\u65e5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='\u5909\u66f4\u65e5'),
        ),
        migrations.AddField(
            model_name='result',
            name='testname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testor.Test', verbose_name='\u30c6\u30b9\u30c8'),
        ),
        migrations.AddField(
            model_name='result',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testor.Member', verbose_name='\u30e6\u30fc\u30b6'),
        ),
    ]
