# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-07 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testor', '0002_auto_20180407_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='method',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u8a66\u9a13\u65b9\u5f0f\u30b3\u30fc\u30c9'),
        ),
    ]
